### PR TITLE
fix: add rememberMe to login

### PR DESCRIPTION
**Pull request by onedr0p**

### CODE REVIEW

**Comment by kashalls** [comment]
This just extends the lifetime of the cookie from 2 hours to 30 days. While 30 days might be a stretch for the lifetime of this container as external-dns probably would update and cause this to refresh, there is a `/api/auth/refresh` that takes the UOS_TOKEN, maybe if we got a better api capture of that in action we could replicate it.

**Comment by onedr0p** [comment]
This can be added after https://github.com/kashalls/external-dns-unifi-webhook/pull/23 is merged and tested.

**Comment by onedr0p** [comment]
I don't see anything on the docs about that refresh ep, so if you want to go down the rabbit hole feel free

https://ubntwiki.com/products/software/unifi-controller/api

**Comment by kashalls** [comment]
If you look into the local console network it calls refreshSesssion if the token is expired for a short time after it was expired. Doesn't seem to take any additional arguments. 

8PsctnY

**Pull request closed without merging**
